name: Extract TWRP Ramdisk

on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 cpio gzip file

      - name: Create output directory
        run: mkdir -p extracted_twrp

      - name: Unpack TWRP image
        run: |
          python3 tools/unpack_bootimg.py \
            -i input/twrp-3.5.2_9-0-ali.img \
            -o extracted_twrp || true

      - name: 🔍 Debug: Show files and types
        run: |
          echo "--- Files inside extracted_twrp ---"
          find extracted_twrp -type f
          echo "--- File types ---"
          find extracted_twrp -type f -exec file {} \;
