# .github/workflows/test-manual.yml
name: Test Manual Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Manual workflow is working"

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full lz4 cpio unzip file

      - name: Clone Android Image Kitchen (AIK)
        run: |
          git clone https://github.com/osm0sis/Android-Image-Kitchen.git AIK
          chmod +x AIK/*.sh

      - name: Copy TWRP image into AIK
        run: |
          mkdir -p input
          cp input/twrp-3.5.2_9-0-ali.img AIK/image.img

      - name: Unpack image using AIK
        run: |
          cd AIK
          ./unpackimg.sh image.img

      - name: Show extracted files
        run: |
          echo "--- Kernel and split info ---"
          ls -lh AIK/split_img
          echo "--- Ramdisk contents ---"
          ls -lh AIK/ramdisk

      - name: Upload extracted ramdisk (optional)
        uses: actions/upload-artifact@v4
        with:
          name: twrp-ramdisk
          path: AIK/ramdisk
