name: Extract TWRP Ramdisk

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full lz4 cpio unzip file

      - name: Clone AIK
        run: |
          git clone https://github.com/osm0sis/Android-Image-Kitchen.git AIK
          chmod +x AIK/unpackimg.sh AIK/repackimg.sh

      - name: Prepare input image
        run: mkdir -p input && cp input/twrp-3.5.2_9-0-ali.img ./AIK/image.img

      - name: Unpack TWRP with AIK
        run: |
          cd AIK
          ./unpackimg.sh image.img

      - name: List unpacked files
        run: |
          echo "--- split_img/ ---"
          ls -lh AIK/split_img
          echo "--- ramdisk/ ---"
          ls -lh AIK/ramdisk
          echo "--- ramdisk file types ---"
          file AIK/ramdisk/* || true

      - name: Upload extracted ramdisk (optional)
        uses: actions/upload-artifact@v4
        with:
          name: twrp-ramdisk
          path: AIK/ramdisk
