name: Repack TWRP Boot Image

on:
  workflow_dispatch:

jobs:
  repack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y abootimg python3

      - name: Create output directory
        run: mkdir -p output

      - name: Repack boot image
        run: |
          cd repack
          python3 ../tools/mkbootimg.py \
          --kernel zImage \
          --ramdisk twrp_ramdisk.cpio.gz \
          --base 0x80000000 \
          --pagesize 2048 \
          --kernel_offset 0x00008000 \
          --ramdisk_offset 0x01000000 \
          --tags_offset 0x00000100 \
          --board MSM8953 \
          --cmdline "console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 androidboot.bootdevice=7824900.sdhci earlycon=msm_hsl_uart,0x78af000 buildvariant=user" \
          --os_version 8.1.0 \
          --os_patch_level 2020-06 \
          -o ../output/zImage_test_twrp.img


      - name: Upload repacked TWRP image
        uses: actions/upload-artifact@v4
        with:
          name: new-twrp.img
          path: output/zImage_test_twrp.img
