name: Unpack Recovery Image

on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create output dir
        run: mkdir -p output

      - name: Run unpacking using local script
        run: |
          python3 tools/extract-bootimg.yml -i stock/recovery.img -o output
          ls output

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: unpacked-recovery
          path: output/
