name: Extract Ramdisk from TWRP Image
on:
  workflow_dispatch:

jobs:
  extract_ramdisk:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Starting ramdisk extraction workflow."

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          # Ensure perl and required archive tools are installed
          sudo apt-get install -y p7zip-full lz4 cpio unzip file perl tar gzip

      - name: Download Android Image Kitchen (AIK) Linux release
        run: |
          # Download the Linux release archive
          # This URL is from the official XDA thread attachments
          curl -L "https://xdaforums.com/attachments/aik-linux-v3-8-all-tar-gz.5317711/" -o AIK-Linux-v3.8-ALL.tar.gz

      - name: Extract AIK archive
        run: |
          # Extract the archive. This will create a directory named 'Android-Image-Kitchen'
          tar -xzvf AIK-Linux-v3.8-ALL.tar.gz
          # Rename the extracted folder to simply 'AIK' for consistency with previous steps
          mv Android-Image-Kitchen AIK

      - name: Make AIK Perl scripts executable
        run: |
          # Change directory to AIK and make Perl scripts executable
          chmod +x AIK/*.pl

      - name: Copy TWRP image into AIK
        run: |
          mkdir -p input
          # Ensure your 'twrp-3.5.2_9-0-ali.img' is indeed in a directory named 'input'
          # at the root of your repository.
          cp input/twrp-3.5.2_9-0-ali.img AIK/image.img

      - name: Unpack image using AIK
        run: |
          cd AIK
          # Execute the unpackimg.pl script using perl
          perl unpackimg.pl image.img

      - name: Show extracted files
        run: |
          echo "--- Kernel and split info ---"
          ls -lh AIK/split_img
          echo "--- Ramdisk contents ---"
          ls -lh AIK/ramdisk

      - name: Upload extracted ramdisk
        uses: actions/upload-artifact@v4
        with:
          name: twrp-ramdisk-extracted
          path: AIK/ramdisk
          retention-days: 5
