name: Extract Ramdisk from TWRP Image
on:
  workflow_dispatch:

jobs:
  extract_ramdisk:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Starting ramdisk extraction workflow."

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          # Added 'perl' to ensure it's installed for AIK scripts
          sudo apt-get install -y p7zip-full lz4 cpio unzip file perl

      - name: Clone Android Image Kitchen (AIK)
        run: |
          git clone https://github.com/osm0sis/Android-Image-Kitchen.git AIK
          # Change .sh to .pl as AIK uses Perl scripts
          chmod +x AIK/*.pl

      - name: Copy TWRP image into AIK
        run: |
          mkdir -p input
          # Ensure your 'twrp-3.5.2_9-0-ali.img' is indeed in a directory named 'input'
          # at the root of your repository.
          cp input/twrp-3.5.2_9-0-ali.img AIK/image.img

      - name: Unpack image using AIK
        run: |
          cd AIK
          # Use 'perl' to execute the unpackimg.pl script
          perl unpackimg.pl image.img

      - name: Show extracted files
        run: |
          echo "--- Kernel and split info ---"
          ls -lh AIK/split_img
          echo "--- Ramdisk contents ---"
          ls -lh AIK/ramdisk

      - name: Upload extracted ramdisk
        uses: actions/upload-artifact@v4
        with:
          name: twrp-ramdisk-extracted
          path: AIK/ramdisk
          retention-days: 5
