name: Extract TWRP Ramdisk

on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 cpio gzip

      - name: Create output directory
        run: mkdir -p extracted_twrp

      - name: Unpack TWRP boot image
        run: |
          python3 tools/unpack_bootimg.py \
            -i input/twrp-3.5.2_9-0-ali.img \
            -o extracted_twrp

      - name: Debug: List everything in extracted_twrp
        run: |
          echo "=== File list ==="
          ls -lh extracted_twrp
          echo "=== File types ==="
          file extracted_twrp/* || true
